apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: tdemo3-aks
  namespace: aks-dev
  labels:
    app.kubernetes.io/part-of: tdemo1
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1701405643107471422"
    kapp.k14s.io/association: v1.4c308b371174f01df53e5a523eeba96d
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
    carto.run/cluster-template-name: config-deliverable-template
    carto.run/resource-name: deliverable-config
    carto.run/supply-chain-name: source-test-scan-to-url
    carto.run/template-kind: ClusterConfigTemplate
    carto.run/template-lifecycle: mutable
    carto.run/workload-name: tdemo3-aks
    carto.run/workload-namespace: aks-dev
spec:
  params:
  - name: gitops_ssh_secret
    value: workload-git-auth
  source:
    git:
      url: https://github.com/raghupemm/tap-app-ops.git
      ref:
        branch: main
    subPath: config/aks-dev/tdemo3-aks

